### ISSUE TITLE
Deployment to proprietary Posit Connect

### ISSUE THREAD

**Issue by xiaohuagong** [DotanOr/DataCheQC#1]
Thanks for your efforts in developing this App and we are able to launch it in an interactive session. However, we have not been able to deploy this App to a proprietary Posit Connect server for testing purpose among multiple persons.  Do you have advice on resolving these issues?

```
* May be unable to deploy package dependency 'bvpSolve'; could not
  determine a repository URL for the source 'CRAN'.

* Unable to determine the source location for some packages. Packages
  should be installed from a package repository like CRAN or a version
  control system. Check that options('repos') refers to a package
  repository containing the needed package versions.
```

**Comment by DotanOr** [comment]
I believe the issue is caused when Posit/rsconnect tries to install the bvpSolve package, but is unable to do so since it has been removed from CRAN. 

To get around this, you can try to install bvpSolve manually by running `devtools::install_github("cran/bvpSolve")` and then running `rsconnect::deployApp()` - as described by [this thread](https://github.com/rstudio/rsconnect/issues/88) on the rsconnect Github repo.
